// Rotas sem parâmetro do SPA (sistema/src/App.tsx) que viram HTML no export
// estático. Rotas com :id (pagamento, inscritos/:id, sorteio/:id...) não dá
// para pré-gerar: o GitHub Pages devolve o 404.html, que é app/not-found.tsx
// renderizando o mesmo SPA, e o React Router resolve a rota no navegador.
// Ao criar uma rota fixa nova no App.tsx, acrescente aqui também.
export const ROTAS_ESTATICAS = [
  "nightrun",
  "regulamento",
  "inscricao",
  "atleta",
  "atleta/login",
  "atleta/dashboard",
  "atleta/pagamentos",
  "admin",
  "admin/login",
  "admin/dashboard",
  "admin/inscritos",
  "admin/inscritos/novo",
  "admin/modalidades",
  "admin/equipes",
  "admin/financeiro",
  "admin/financeiro/faturas",
  "admin/financeiro/relatorios",
  "admin/financeiro/definicoes",
  "admin/financeiro/cobrancas",
  "admin/verificar-pagamentos",
  "admin/cobranca-pendentes",
  "admin/kits",
  "admin/presenca",
  "admin/card-euvou",
  "admin/mensagens",
  "admin/mensagens/personalizadas",
  "admin/whatsapp",
  "admin/midias",
  "admin/export",
  "admin/camisetas",
  "admin/usuarios",
  "admin/sorteios",
  "admin/lotes",
  "admin/cupons",
  "admin/integracoes",
  "admin/modo-manutencao",
  "admin/configuracoes",
  "admin/dev",
];
